kind: Namespace
apiVersion: v1
metadata:
  name: cep-project2
  labels:
    slearn: cep-project2
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: allow-traffic-in-ns
 namespace: cep-project2
spec:
 podSelector: {}
 policyTypes:
  - Ingress
 ingress:
  - from:
     - namespaceSelector:
         matchLabels:
           slearn: cep-project2
